# nginx/nginx.conf

events {
    worker_connections 1024;
}

http {

    # Definir el grupo de servidores backend (las 3 instancias de la API)
    upstream api_cluster {
        # Algoritmo round-robin (es el predeterminado en Nginx)
        server api1:3000;
        server api2:3000;
        server api3:3000;
    }

    server {
        # Nginx escucha en el puerto 80
        listen 80;

        # Manejar todas las rutas
        location /api/ {
            # Redirigir al grupo de APIs
            proxy_pass http://api_cluster/;

            # Cabeceras necesarias para que la API sepa la IP real del cliente
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Soporte para todos los métodos HTTP
            proxy_method $request_method;

            # Timeouts
            proxy_connect_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
}